version: '3.6'
services:
  #main:
    # container_name: main
    # build:
    #   context: .
    #   target: development
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # ports:
    #   - '3000:3000'
    # command: npm run start:dev
    # networks:
    #   - webnet
    # depends_on:
    #   - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'bot'

networks:
  webnet:
volumes:
  pgdata:

